export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const SORT_PRODUCTS = "SORT_PRODUCTS"
export const UPDATE_USER_NAVBAR = 'UPDATE_USER_NAVBAR'
export const UPDATE_PRICE = "UPDATE_PRICE"